import CONSTANTS from "../constants/const";
export const fakedata = [
  {
    author: "Chinua Achebe",
    country: "Nigeria",
    imageLink: `${CONSTANTS.BASEURL}/static/images/default.png`,
    language: "English",
    link: "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    pages: 209,
    title: "Things Fall Apart",
    year: 1958,
  },
  {
    author: "Hans Christian Andersen",
    country: "Denmark",
    imageLink: `${CONSTANTS.BASEURL}/static/images/default.png`,
    language: "Danish",
    link: "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    pages: 784,
    title: "Fairy tales",
    year: 1836,
  },
  {
    author: "Dante Alighieri",
    country: "Italy",
    imageLink: `${CONSTANTS.BASEURL}/static/images/default.png`,
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    pages: 928,
    title: "The Divine Comedy",
    year: 1315,
  },
  {
    author: "Unknown",
    country: "Sumer and Akkadian Empire",
    imageLink: `${CONSTANTS.BASEURL}/static/images/default.png`,
    language: "Akkadian",
    link: "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
    pages: 160,
    title: "The Epic dfs Gilgamesh",
    year: -1700,
  },
  {
    author: "Unknown",
    country: "Achaemenid Empire",
    imageLink: `${CONSTANTS.BASEURL}/static/images/default.png`,
    language: "Hebrew",
    link: "https://en.wikipedia.org/wiki/Book_of_Job\n",
    pages: 176,
    title: "The Bookghgh Of Job",
    year: -600,
  },
  {
    author: "Unknown",
    country: "India/Iran/Iraq/Egypt/Tajikistan",
    imageLink: `${CONSTANTS.BASEURL}/static/images/default.png`,
    language: "Arabic",
    link: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    pages: 288,
    title: "One Thouddfsand and One Nights",
    year: 1200,
  },
  {
    author: "Unknown",
    country: "Achaemenid Empire",
    imageLink: `${CONSTANTS.BASEURL}/static/images/default.png`,
    language: "Hebrew",
    link: "https://en.wikipedia.org/wiki/Book_of_Job\n",
    pages: 176,
    title: "The Book Offfff Job",
    year: -600,
  },
  {
    author: "Unknown",
    country: "India/Iran/Iraq/Egypt/Tajikistan",
    imageLink: `${CONSTANTS.BASEURL}/static/images/default.png`,
    language: "Arabic",
    link: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    pages: 288,
    title: "One Thouffsand and One Nights",
    year: 1200,
  },
  {
    author: "Unknown",
    country: "Achaemenid Empire",
    imageLink: `${CONSTANTS.BASEURL}/static/images/default.png`,
    language: "Hebrew",
    link: "https://en.wikipedia.org/wiki/Book_of_Job\n",
    pages: 176,
    title: "The Booasssk Of Job",
    year: -600,
  },
  {
    author: "Unknown",
    country: "India/Iran/Iraq/Egypt/Tajikistan",
    imageLink: `${CONSTANTS.BASEURL}/static/images/default.png`,
    language: "Arabic",
    link: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    pages: 288,
    title: "One Thoasusand and One Nights",
    year: 1200,
  },
  {
    author: "Unknown",
    country: "Achaemenid Empire",
    imageLink: `${CONSTANTS.BASEURL}/static/images/default.png`,
    language: "Hebrew",
    link: "https://en.wikipedia.org/wiki/Book_of_Job\n",
    pages: 176,
    title: "The Booaskert Of Job",
    year: -600,
  },
  {
    author: "Unknown",
    country: "India/Iran/Iraq/Egypt/Tajikistan",
    imageLink: `${CONSTANTS.BASEURL}/static/images/default.png`,
    language: "Arabic",
    link: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    pages: 288,
    title: "One Thouaassand and One Nights",
    year: 1200,
  },
];
